variables:
- group: common
- template: /.azuredevops/variables-global.yml

parameters:
- name: checkoutRef
  type: string
  default: refs/tags/$(LATEST_RELEASE_TAG)

resources:
  repositories:
  - repository: release_repo
    type: github
    endpoint: ROCm
    name: ROCm/aomp
    ref: ${{ parameters.checkoutRef }}
  - repository: llvm-project_repo
    type: github
    endpoint: ROCm
    name: ROCm/llvm-project
    ref: ${{ parameters.checkoutRef }}

trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/aomp.yml
    parameters:
      checkoutRepo: release_repo
      checkoutRef: ${{ parameters.checkoutRef }}
