variables:
- group: common
- template: /.azuredevops/variables-global.yml

parameters:
- name: gtestVersion
  type: string
  default: main

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_DEPENDENCIES_PATH }}/gtest.yml
    parameters:
      gtestVersion: ${{ parameters.gtestVersion }}
