variables:
- group: common
- template: /.azuredevops/variables-global.yml

parameters:
- name: lapackVersion
  type: string
  default: 3.9.1

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_DEPENDENCIES_PATH }}/lapack.yml
    parameters:
      lapackVersion: ${{ parameters.lapackVersion }}
