variables:
- group: common
- template: /.azuredevops/variables-global.yml

resources:
  repositories:
  - repository: release_repo
    type: github
    endpoint: ROCm
    name: ROCm/aomp
    ref: aomp-dev
  - repository: llvm-project_repo
    type: github
    endpoint: ROCm
    name: ROCm/llvm-project
    ref: amd-staging
  pipelines:
  - pipeline: rocr-runtime_pipeline
    source: \ROCR-Runtime
    trigger:
      branches:
        include:
        - master

# this job will only be triggered after successful build sequence of llvm-project and ROCR-Runtime

trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/aomp.yml
    parameters:
      checkoutRepo: release_repo
